### ISSUE TITLE
Issue with git sync

### ISSUE THREAD

**Issue by viveksachdeva** [jdigger/git-process#139]
I installed git process on mac. new-fb works fine but when I do git sync, I am getting following error:

Doing rebase-based sync
/usr/local/lib/ruby/gems/2.3.0/gems/git-process-lib-2.0.4/lib/git-process/git_branch.rb:65:in `<=>': undefined method `name' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/git-process-lib-2.0.4/lib/git-process/git_branches.rb:66:in `=='
	from /usr/local/lib/ruby/gems/2.3.0/gems/git-process-lib-2.0.4/lib/git-process/git_branches.rb:66:in `!='
	from /usr/local/lib/ruby/gems/2.3.0/gems/git-process-lib-2.0.4/lib/git-process/git_branches.rb:66:in `include?'
	from /usr/local/lib/ruby/gems/2.3.0/gems/git-process-lib-2.0.4/lib/git-process/git_lib.rb:130:in `previous_remote_sha'
	from /usr/local/lib/ruby/gems/2.3.0/gems/git-process-lib-2.0.4/lib/git-process/syncer.rb:65:in `rebase_sync'
	from /usr/local/lib/ruby/gems/2.3.0/gems/git-process-lib-2.0.4/lib/git-process/syncer.rb:37:in `do_sync'
	from /usr/local/lib/ruby/gems/2.3.0/gems/git-process-lib-2.0.4/lib/git-process/sync_process.rb:50:in `runner'
	from /usr/local/lib/ruby/gems/2.3.0/gems/git-process-lib-2.0.4/lib/git-process/git_process.rb:38:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/git-sync-2.0.4/bin/git-sync:38:in `<top (required)>'
	from /usr/local/bin/git-sync:23:in `load'
	from /usr/local/bin/git-sync:23:in `<main>'

**Comment by viveksachdeva** [comment]
@jdigger : Thanks.. Downgrading ruby worked

**Comment by jdigger** [comment]
This is fixed in v3.0.0
