### ISSUE TITLE
gitProcess.integrationBranch branch setup not working

### ISSUE THREAD

**Issue by sikarwarvimal** [jdigger/git-process#152]
Hi Jim, I hope you are doing good :)

I have been such a big fan for git-process tool and I use all the time with the `master` branch but recently I had to work with `develop` branch and when I set the `integrationBranch` as `develop` then none of the git-process command works and I see below error.

```/Users/vimal/.rvm/gems/ruby-2.4.1/gems/git-process-lib-3.0.1/lib/git-process/git_process.rb:117:in `should_remove_master?': undefined method `contains_all_of' for nil:NilClass (NoMethodError)
        from /Users/vimal/.rvm/gems/ruby-2.4.1/gems/git-process-lib-3.0.1/lib/git-process/git_process.rb:79:in `verify_preconditions'
        from /Users/vimal/.rvm/gems/ruby-2.4.1/gems/git-process-lib-3.0.1/lib/git-process/sync_process.rb:34:in `verify_preconditions'
        from /Users/vimal/.rvm/gems/ruby-2.4.1/gems/git-process-lib-3.0.1/lib/git-process/git_process.rb:36:in `run'
        from /Users/vimal/.rvm/gems/ruby-2.4.1/gems/git-sync-3.0.1/bin/git-sync:38:in `<top (required)>'
        from /Users/vimal/.rvm/gems/ruby-2.4.1/bin/git-sync:23:in `load'
        from /Users/vimal/.rvm/gems/ruby-2.4.1/bin/git-sync:23:in `<main>'
        from /Users/vimal/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
        from /Users/vimal/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'```

Can you please take a look? 

I hope it would be a quick fix for you :)

Thanks,
Vimal.

**Comment by sikarwarvimal** [comment]
I changed the plan and will use the `master` itself to create `feature branches` instead of `develop`.

Thanks!

**Comment by jdigger** [comment]
Nice simple fix. 😸  Not sure why the `integrationBranch` setting didn't work for that.
